### ISSUE TITLE
Invoking a milestone without a function?

### ISSUE THREAD

**Issue by lolmaus** [salsify/milestones#22]
Hi!

When I ran into the necessity to step through stages of a promise with multiple thens, I made a custom solution similar to Milestones.

It had a slight difference, though.

Instead of this:

```js
await milestone(Save, () => saveData());
```

it allowed to do this:

```js
await milestone(Save);
saveData();
```

I believe, this subtle change makes the code much easier to read and to reason about.

I haven't tried Milestones yet and not sure if this invocation style is supported. But the API docs do list the callback as a mandatory argument.

**Comment by dfreeman** [comment]
It's not necessarily the easiest thing to pick out, since the header is gnarly and long, but `milestone` has two signatures, and the second one lets you skip the callback: https://salsify.github.io/milestones/docs/api/modules/@milestones/core#milestone

The `Points in Time` section that introduces how milestones work also starts out with callback-less milestones in [its examples](https://salsify.github.io/milestones/docs#points-in-time).

The reason we do include the signature that wraps the callback is that this makes it possible to synchronize with points in time both before _and after_ the promise resolves, as well as keeping the callback from being invoked at all if you want to e.g. skip a pause or mock the result in a particular test.

**Comment by lolmaus** [comment]
Thx for clarification!

It might make sense to use the no-callback example in the introduction.
